version: "3.1"
services:
    mailpit:
        image: 'axllent/mailpit:v1.7'
        ports:
            - '8025:8025'
            - '1025:1025'
    mysql:
        image: mysql:5.7
        container_name: easyappointments-database
        volumes:
            - mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=easyappointments
        ports:
            - "8001:3306"
    php-fpm:
        build:
            dockerfile: Dockerfile.production
        working_dir: /var/www/html
        volumes:
            - '.:/var/www/html'
            - './docker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini'
        environment:
            - DEBUG_MODE=TRUE
            - SKIP_UNZIP=TRUE
            - GOOGLE_SYNC_FEATURE=TRUE
            - STRIPE_API_KEY=b3657af6-bdaf-4b45-b645-e03a474d39c3

    nginx:
        image: 'nginx:1.23.3-alpine'
        working_dir: /var/www/html
        volumes:
            - '.:/var/www/html'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8000:80'
    phpmyadmin:
        image: 'phpmyadmin:5.2.0'
        restart: always
        ports:
            - '8002:80'
        environment:
            - 'PMA_HOST=mysql'
networks:
    internal:
        driver: bridge
volumes:
    mysql:
