services:
    mailpit:
        image: 'axllent/mailpit:v1.7'
        ports:
            - '8025:8025'
            - '1025:1025'
        volumes:
            - './mailpit.conf:/tmp/mailpit.conf'
        env_file:
            - .env
    mysql:
        image: mariadb:10.10
        container_name: easyappointments-database
        volumes:
            - mysql:/var/lib/mysql
        ports:
            - '8001:3306'
        env_file:
            - .env
    php-fpm:
        build:
            dockerfile: Dockerfile.production
        working_dir: /var/www/html
        volumes:
            - '.:/var/www/html'
            - './docker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini'
        env_file:
            - .env
        extra_hosts:
            - host.docker.internal:host-gateway

    swagger-ui:
        platform: linux/amd64
        image: swaggerapi/swagger-ui:v5.10.5
        ports:
            - "8004:8080"
        volumes:
            - ./openapi.yml:/usr/share/nginx/html/openapi.yml
        environment:
            API_URL: openapi.yml
    nginx:
        image: 'nginx:1.23.3-alpine'
        working_dir: /var/www/html
        volumes:
            - '.:/var/www/html'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8000:80'
    phpmyadmin:
        image: 'phpmyadmin:5.2.0'
        restart: always
        ports:
            - '8002:80'
        environment:
            - 'PMA_HOST=mysql'
            - 'UPLOAD_LIMIT=204800K'
        env_file:
            - .env
networks:
    internal:
        driver: bridge
volumes:
    mysql:
